docs(@deip/auth-module): add docs
DEIPworld/casimir-frontend pull request #464
Opened 2022-03-04 17:19 UTC by Vadim-SVB

2022-03-10 22:58 UTC, euheny requested changes

2022-03-10 22:58 UTC, euheny commented on packages/casimir/modules/auth/lib/components/AuthChangePassword.vue
> +       * Fires on form submission and
and? водимо что-то с текстом не совсем ок ))

2022-03-10 22:58 UTC, euheny commented on packages/casimir/modules/auth/lib/components/AuthChangePassword.vue
> +       * Triggers emitSuccess/emitError events and loading screen
state - у нас нет скринов загрузки

2022-03-10 22:58 UTC, euheny commented on packages/casimir/modules/auth/lib/components/AuthPasswordRestore.vue
> +       * @example ":formGap=48"
1 - пропсы в классическом темлейте пишутся кебабом, в jsx - камелом
2 - если уж приводить экземпл то лучше с кодом самого компонента или же просто значение

2022-03-10 22:58 UTC, euheny commented on packages/casimir/modules/auth/lib/components/AuthPasswordRestore.vue
> +       * @example ":fieldsGap=8"
см комментарий к `formGap` и отсмотреть остальные пропсы

2022-03-10 22:58 UTC, euheny commented on packages/casimir/modules/auth/lib/components/AuthChangePassword.vue
> +  * @displayName  AuthChangePassword
> Note the use of the @displayName tag to change the displayed name of your component
короч его имеет смысл использовать только если хочешь чтобы отображение было отличным от name. относится ко всем компонентам

2022-03-11 07:02 UTC, Vadim-SVB commented on packages/casimir/modules/auth/lib/components/AuthChangePassword.vue
> +       * Fires on form submission and
Точно ) Исправил

2022-03-11 07:04 UTC, Vadim-SVB commented on packages/casimir/modules/auth/lib/components/AuthPasswordRestore.vue
> +       * @example ":formGap=48"
убрал, хотел написать default без @  что бы не писать @example 48, но не знал нужно ли

2022-03-11 07:05 UTC, Vadim-SVB commented on packages/casimir/modules/auth/lib/components/AuthChangePassword.vue
> +  * @displayName  AuthChangePassword
Убрал

2022-03-11 07:45 UTC, euheny approved these changes

2022-03-11 07:45 UTC, merged