docs(@deip/bookmarks-module): add docs
DEIPworld/casimir-frontend pull request #473
Opened 2022-03-10 11:19 UTC by Vadim-SVB

2022-03-10 22:19 UTC, euheny requested changes

2022-03-10 22:19 UTC, euheny commented on packages/casimir/modules/bookmarks/lib/components/ToggleBookmarkBtn.vue
> +      *
лишняя строка

2022-03-10 22:59 UTC, euheny requested changes

2022-03-10 22:59 UTC, euheny commented on packages/casimir/modules/bookmarks/lib/components/ToggleBookmarkBtn.vue
> +  * @displayName  ToggleBookmarkBtn
displayName - только если надо изменить отображение имени  компонента

2022-03-11 06:46 UTC, Vadim-SVB commented on packages/casimir/modules/bookmarks/lib/components/ToggleBookmarkBtn.vue
> +      *
Убрал

2022-03-11 06:47 UTC, Vadim-SVB commented on packages/casimir/modules/bookmarks/lib/components/ToggleBookmarkBtn.vue
> +  * @displayName  ToggleBookmarkBtn
Убрал, буду знать теперь

2022-03-11 07:44 UTC, euheny approved these changes

2022-03-11 07:44 UTC, merged