docs(@deip/domains-module): add docs
DEIPworld/casimir-frontend pull request #485
Opened 2022-03-16 12:31 UTC by Vadim-SVB

2022-03-16 13:14 UTC, elena-vlasova requested changes

2022-03-16 13:14 UTC, elena-vlasova commented on packages/casimir/modules/domains/lib/components/Selector/DomainSelector.vue
> +   * @requires vuetify-extended
Domain - это дисциплина типа физика, химия и т.п.. Про группы и проекты убери.
И это компонент для выбора - selector

2022-03-16 13:14 UTC, elena-vlasova commented on packages/casimir/modules/domains/lib/components/Selector/DomainSelector.vue
> +   * @requires vuetify-extended
Может я чего-то не поняла, зачем прописывать `requires`?
https://vue-styleguidist.github.io/docs/Documenting.html#composable-components
Тут написано, что в requires прописываются компоненты, которые используются только в текущем компоненте и для которых не должно быть отдельного дока.

2022-03-16 13:14 UTC, elena-vlasova commented on packages/casimir/modules/domains/lib/components/Selector/DomainSelector.vue
>          this.$emit('input', value);
https://vue-styleguidist.github.io/docs/Documenting.html#events
Event надо описывать перед `this.$emit('input', value);`

2022-03-16 19:07 UTC, Vadim-SVB commented on packages/casimir/modules/domains/lib/components/Selector/DomainSelector.vue
> +   * @requires vuetify-extended
Точно, удалю, спасибо

2022-03-16 19:11 UTC, Vadim-SVB commented on packages/casimir/modules/domains/lib/components/Selector/DomainSelector.vue
>          this.$emit('input', value);
исправил

2022-03-17 07:31 UTC, euheny requested changes

2022-03-17 07:31 UTC, euheny commented on packages/casimir/modules/domains/lib/components/Selector/DomainSelector.vue
> +       *  @property {string} item id
отступ

2022-03-17 10:32 UTC, elena-vlasova commented on packages/casimir/modules/domains/lib/components/Selector/DomainSelector.vue
>          this.$emit('input', value);
Перед этой строкой не прописан комментарий. А стоило бы, так как есть параметр.
@event input прописывать не обязательно, стринговое название ивента подтянется

2022-03-17 10:32 UTC, elena-vlasova commented on packages/casimir/modules/domains/lib/components/Selector/DomainSelector.vue
> +       * @property {array} selected items
`Array`

2022-03-21 07:51 UTC, euheny requested changes

2022-03-21 07:51 UTC, euheny commented on packages/casimir/modules/domains/lib/components/Selector/DomainSelector.vue
> +         * @event
@event name - имя прописывается (если исходить из доков)
при этом
> If the event is explicitly specified, no need to tell styleguidist what it is.
тоесть если имя евента определено, то его в принципе можно не прописывать

2022-03-21 14:31 UTC, elena-vlasova approved these changes

2022-03-22 07:31 UTC, euheny approved these changes

2022-03-22 07:31 UTC, merged