docs(@deip/vuetify-extended): add docs - part 2
DEIPworld/casimir-frontend pull request #494
Opened 2022-03-21 09:25 UTC by Vadim-SVB

2022-03-21 14:58 UTC, elena-vlasova requested changes
В доке к методу надо использовать @param, @arg или @argument, а не @property. 
Тип `string` пишется с маленькой буквы

2022-03-21 14:58 UTC, elena-vlasova commented on packages/casimir/plugins/VuetifyExtended/lib/components/VexMiniMeta/VexMiniMetaItem.vue
> +      */
Съехала строка комментария

2022-03-21 14:58 UTC, elena-vlasova commented on packages/casimir/plugins/VuetifyExtended/lib/components/VexMiniMeta/VexMiniMeta.vue
> +   * Сomponent that shows additional data in the user interface
Лучше написать про список текста с иконками

2022-03-21 14:58 UTC, elena-vlasova commented on packages/casimir/plugins/VuetifyExtended/lib/components/VexRichedit/VexRichedit.vue
> +           * @property {String} lazyValue input data
`string`

2022-03-21 14:58 UTC, elena-vlasova commented on packages/casimir/plugins/VuetifyExtended/lib/components/VexRichedit/VexRichedit.vue
> +       * when text field is focused again
Мне кажется, в описании функции не нужно писать, где она используется

2022-03-21 14:58 UTC, elena-vlasova commented on packages/casimir/plugins/VuetifyExtended/lib/components/VexSection/VexSection.vue
> +       * @example 'amber darken-3' or '#FFE082', rgba(255, 224, 130, 1)'
Не хватает кавычки

2022-03-21 14:58 UTC, elena-vlasova commented on packages/casimir/plugins/VuetifyExtended/lib/components/VexSection/VexSectionSplit.vue
> +       * @example 'amber darken-3' or '#FFE082', rgba(255, 224, 130, 1)'
Тут тоже не хватает кавычки

2022-03-22 11:14 UTC, Vadim-SVB commented on packages/casimir/plugins/VuetifyExtended/lib/components/VexTimeline/VexTimelineAdd.vue
> +         * @event
исправил, пересмотрел везде

2022-03-22 11:15 UTC, Vadim-SVB commented on packages/casimir/plugins/VuetifyExtended/lib/components/VexRichedit/VexRichedit.vue
> +           * @property {String} lazyValue input data
везде исправил

2022-03-22 17:18 UTC, elena-vlasova approved these changes

2022-03-24 09:08 UTC, merged