remove wrong usage of @requires from docs
DEIPworld/casimir-frontend pull request #502
Opened 2022-03-24 13:58 UTC by Vadim-SVB

check usage of @property, @param and @arg

2022-03-25 15:08 UTC, elena-vlasova requested changes

2022-03-25 15:08 UTC, elena-vlasova commented on packages/casimir/modules/contract-agreements/lib/components/Table/ContractsTable.vue
> +         * @property {object} contract data
`Object`

2022-03-25 15:08 UTC, elena-vlasova commented on packages/casimir/modules/contract-agreements/lib/components/Table/ContractsTable.vue
> +       * @param {object} contract data
`Object`

2022-03-25 15:08 UTC, elena-vlasova commented on packages/casimir/modules/contract-agreements/lib/components/Table/ContractsTable.vue
> +       * @param {object} contract data
`Object`

2022-03-25 15:08 UTC, elena-vlasova commented on packages/casimir/modules/domains/lib/components/Selector/DomainSelector.vue
> +       * @param {String} item id
`string`

2022-03-25 15:08 UTC, elena-vlasova commented on packages/casimir/modules/wallet/lib/components/Balances/Balances.vue
> +       * @param {object} balance data
`Object`

2022-03-26 12:23 UTC, Vadim-SVB commented on packages/casimir/modules/contract-agreements/lib/components/Table/ContractsTable.vue
> +         * @property {object} contract data
Дополнил новыми файлами где нашел что `Object` и `Array` написано со строчной буквы а  `String` с заглавной

2022-03-28 07:54 UTC, elena-vlasova approved these changes

2022-03-29 07:25 UTC, merged