Fix/balance card
DEIPworld/casimir-frontend pull request #506
Opened 2022-03-30 08:45 UTC by elena-vlasova

2022-03-30 09:15 UTC, Vadim-SVB submitted a review, later dismissed

2022-03-30 10:23 UTC, euheny requested changes

2022-03-30 10:23 UTC, euheny commented on packages/casimir/modules/wallet/lib/components/Balances/BalanceCard.vue
> +        min-height="184px"
можно так же в styles убрать

2022-04-06 10:44 UTC, euheny approved these changes

2022-04-06 10:44 UTC, merged