feat: teams-module README.md is ready
DEIPworld/casimir-frontend pull request #550
Opened 2022-05-20 08:23 UTC by ShmidtAlex

2022-05-24 10:26 UTC, elena-vlasova requested changes

2022-05-24 10:26 UTC, elena-vlasova commented on packages/casimir/modules/teams/README.md
> +The module creates store for two new entities called `teams` and `currentUserTeams` and also adds new scope
currentUserTeams больше нет: он не правильно работал и не использовался

2022-05-24 10:26 UTC, euheny requested changes

2022-05-24 10:26 UTC, euheny commented on packages/casimir/modules/teams/README.md
> +The module creates store for two new entities called `teams` and `currentUserTeams` and also adds new scope
currentUserTeams больше нет

2022-06-01 09:56 UTC, elena-vlasova approved these changes

2022-06-01 09:56 UTC, merged