feat(@packages/casmir): project content draft moderation
DEIPworld/casimir-frontend pull request #564
Opened 2022-05-30 10:44 UTC by StasDachinsky

2022-05-30 11:42 UTC, elena-vlasova commented on packages/common/constants/lib/project-content.js
>  });
Для чего эти статусы, если драфт не станет контентом без пройденной модерции?

2022-05-30 13:36 UTC, StasDachinsky commented on packages/common/constants/lib/project-content.js
>  });
Возможность убрать контент из листингов / не показывать на сайте после минта

2022-05-31 07:06 UTC, euheny commented on packages/common/constants/lib/project-content.js
>  });
драфт это не статус айтема, а тип и не является связанным с модерацией (причина существования драфта может быть иной). соответсвенно предполагаю три потенциальных пути развития:
- для nftItems и nftItemsDrafts используется два роута, что гарантировано снимает возможность их смешивания (а статусы у итемов могут отвечать за что угодно)
- используется один роут по умолчанию отдающий только nftItems и по запросу либо подмешивает драфты `withDrafts` или возвращает только их `onlyDrafts` - имхо усложнение
- гибридный - в сервисе три метода: получение айтемов, получение драфтов, сервис подмешивания. соответственно вызывается требующийся метод по надобности

предлагаю остановиться на первом, и реализовать третий если он понадобится

2022-05-31 07:11 UTC, elena-vlasova commented on packages/common/constants/lib/project-content.js
>  });
nftItems и nftItemsDrafts нельзя смешать, у них будут разные схемы(

мой вопрос был конкретно про эту константу, решили пока оставить

2022-06-01 11:36 UTC, d-tsaruk commented on packages/casimir/models/command/lib/impl/CreateDraftCmd.js
> +    if (status) {
можете кидаться в меня ссаными тапками, но я буду придираться к кодстайлу)))
условия, циклы и любые логически законченные блоки кода выделяются пустой строкой

2022-06-01 15:52 UTC, elena-vlasova requested changes
Не добавил новые команды в commands.js и serializations.js

2022-06-03 03:33 UTC, egor-anikey approved these changes

2022-06-03 10:12 UTC, merged